name: delivoo_stores
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.1+68
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  animation_wrappers: ^3.0.0
  app_settings: ^4.2.0
  avatar_glow: ^2.0.2
  background_location: ^0.13.0
  # bloc: ^8.1.2
  cached_network_image: ^3.3.1
  charts_flutter: ^0.12.0
  cloud_firestore: ^5.1.0
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^8.2.2
  equatable: ^2.0.5
  firebase_analytics: ^11.2.0
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.3
  firebase_messaging: ^15.0.3
  firebase_messaging_platform_interface: null
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.6
  flutter_callkit_incoming: ^1.0.2+2
  flutter_feather_icons: ^2.0.0+1
  # flutter_google_places: ^0.3.0
  flutter_local_notifications: ^9.9.1
  flutter_phoenix: ^1.1.1
  flutter_polyline_points: ^1.0.0
  flutter_progress_hud: ^2.0.2
  flutter_staggered_animations: ^1.0.0
  fluttertoast: ^8.1.3
  font_awesome_flutter: ^10.7.0
  geolocator: ^9.0.1
  google_fonts: ^4.0.4
  # google_maps_flutter: ^2.7.0
  # grouped_buttons: ^1.0.4
  http: ^0.13.5
  image_picker: ^1.1.2
  intl: ^0.17.0
  json_annotation: ^4.5.0
  libphonenumber: ^2.0.2
  location: ^7.0.0
  location_permissions: ^4.0.1
  mobile_number_picker: ^0.0.1+5
  mobile_scanner: ^2.1.0
  new_version: ^0.3.1
  path_provider: ^2.0.10
  # payu_checkoutpro_flutter: 1.0.2
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  place_picker: ^0.10.0
  platform_device_id: ^1.0.1
  provider: ^6.1.2
  razorpay_flutter: ^1.3.7
  shared_preferences: ^2.2.3
  syncfusion_flutter_datagrid: ^20.3.49
  toggle_switch: ^2.0.1
  url_launcher: ^6.3.0
  webview_flutter: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  shimmer: ^3.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "images/logos/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/account/
    - images/address/
    - images/custom/
    - images/footermenu/
    - images/icons/
    - images/logos/
